- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
- supports only string as key
Example:
```scala
interface Test {
values(obj: { [ key: string ] : string }): number;
}
```
> Add partial support for associative array

- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
Fix duplicate detection for following example:
```
interface Selection<Datum> {
attr(name: string, value: Primitive): Selection<Datum>;
attr(name: string, value: (datum: Datum, index: number, outerIndex: number) => Primitive): Selection<Datum>;
}
```
Expected: Both methods generated.
> Fix same param name, but different type

- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
Converts to js.Array[T] If all parameters are same like [number,number]
otherwise jsArray[Any]
until scala.js tuple is implemented and released
> Support for tuples as js.Tuple

- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
- accept d.ts without module declaration block (omit export keyword)
- accept `null` and `undefined` as types
> initial Typescript2 support

- build.sbt
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Printer.scala
- src/test/resources/samples/modifiers.ts
- src/test/resources/samples/modifiers.ts.scala
- src/test/scala/org/scalajs/tools/tsimporter/ImporterSpec.scala
Parse "public", "protected" as well as "readonly" modifiers and
translate the two latter into Scala's protected modifier and field
declaration with "val" instead of "var". Similarly parse "const"
declarations and translate them to "val" fields.
---
Some changes made to facilitate generating a facade for [monaco.d.ts](https://github.com/Microsoft/monaco-editor/blob/06c48a7281d5728ad9f46185330be6e2ada29334/monaco.d.ts) as part of scalameta/metadoc#17
> Add support for modifiers and const declarations

- samples/never.ts
- samples/never.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
Converts the `never` type to `Nothing` type.
[The `never` type](https://www.typescriptlang.org/docs/handbook/basic-types.html#never) is a bottom type and can represent the types of value that never occurs, just like [the `Nothing` type](http://www.scala-lang.org/api/2.12.3/scala/Nothing.html) do so in Scala.
Some example of using `never` in type definitions. 
* To prevent using a method in sub class https://github.com/sudo-suhas/elastic-builder/blob/4c454fd3c345ae7de09cd5ad27dcac9479a71cf6/src/index.d.ts#L1394
* To indicate a function that shutdown the system (hence the return value can't be used) https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1aefe0126e5e4ea8fbf0e98661e12439c42dd4e3/types/node/index.d.ts#L459
> Add support for never type

- samples/modifiers.ts
- samples/modifiers.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
* Add `export let myValue: string` support
* I think it is better to make the `let`-exported values read-only (converted to`def myVar: ... `), since the value may be updated within the module.
* Add `export let myModule: { ... }` support
* Add `export const myModule: { ... }` support, which I suppose it was missed in #38 for some reason.
> Add support for "export let" and "export const" for modules

- samples/thistype.ts
- samples/thistype.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Printer.scala
Converts TypeScript's the polymorphic `this` type to Scala's `this.type`.
The [polymorphic this type](https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types) is useful to express hierarchical fluent interfaces easily.
Use cases
* [jQuery's index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f02ac07f965ae89a935b1016130f03ce7387bd7b/types/jquery/index.d.ts#L2981)
* [pixi.js.d.ts](https://github.com/pixijs/pixi-typescript/blob/d76f75ccef19d46b5a793d73803661c57480a3a7/pixi.js.d.ts#L414)
* [archiver's index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f02ac07f965ae89a935b1016130f03ce7387bd7b/types/archiver/index.d.ts#L26)
> Add support for the polymorphic this type

- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
Occurs in TS compiler generated d.ts files i.e. seen in https://github.com/PAIR-code/deeplearnjs
> Allow parsing of ambient declarations starting with "export declare"

- samples/jsglobal.ts
- samples/jsglobal.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Printer.scala
Instead of extending from deprecated js.GlobalScope.
As discussed in https://github.com/sjrd/scala-js-ts-importer/pull/43#pullrequestreview-68755760
> Generate @JSGlobalScope annotation for global vars and functions

- samples/jsglobal.ts.scala
- samples/modifiers.ts.scala
- samples/never.ts.scala
- samples/overrides.ts.scala
- samples/stringlit.ts.scala
- samples/then.ts.scala
- samples/thistype.ts.scala
- src/test/scala/org/scalajs/tools/tsimporter/ImporterSpec.scala
Again related to #43 I have naming conflicts in the samples caused by multiple globals each creating an `Importedjs` object.
So my suggestion would be to just move everything into its own package.
> Put samples into individual packages to avoid naming conflicts

- samples/intersectiontype.ts
- samples/intersectiontype.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Printer.scala
Convert the intersection type `A & B & C` into `A with B with C`.
It can be used to express using mixins, as seen in [jQuery](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/25b68c5aa3cfc9454672ef909568bca341a57ee0/types/jquery/index.d.ts#L2668), [React](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3ad090bdf675a2ddd7c4fcb5ccee9d4a3bb23b1d/types/react/index.d.ts#L210) or [Archiver](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f02ac07f965ae89a935b1016130f03ce7387bd7b/types/archiver/index.d.ts#L43)
> Add support for the intersection type `A & B`

- samples/modifiers.ts
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
Compiler generated .d.ts files contain private methods/fields in order to avoid name collisions when subclassing in TypeScript https://github.com/Microsoft/TypeScript/issues/1867. The type of private fields is not included.
The approach in this PR is to just ignore them.
> Parse and ignore private members

- samples/keyof.ts
- samples/keyof.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
TypeScript 2.1 introduced [index type query and indexed access type](https://github.com/Microsoft/TypeScript/pull/11929)(i.e. `keyof` keyword). This pull request adds supports for it.
```typescript
interface Thing {
name: string;
width: number;
height: number;
inStock: boolean;
}
type K1 = keyof Thing;  // "name" | "width" | "height" | "inStock"
type K2 = keyof Thing[];  // "length" | "push" | "pop" | "concat" | ...
type K3 = keyof { [x: string]: Thing };  // string
type P1 = Thing["name"];  // string
type P2 = Thing["width" | "height"];  // number
type P3 = Thing["name" | "inStock"];  // string | boolean
type P4 = string["charAt"];  // (pos: number) => string
type P5 = string[]["push"];  // (...items: string[]) => number
```
```scala
object Keyof extends js.Object {
type K1 = String
type …
```
> Add supports for index type query and indexed access type

- samples/extendsobject.ts
- samples/extendsobject.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
Some type definition of major library(e.g. lodash, jQuery) use `extends object`.
```typescript
at<T extends object>(
object: T | null | undefined,
...props: Array<Many<keyof T>>
): Array<T[keyof T]>;
```
Because current scala-js-ts-importer converts `object` to `object`, converted file is not compilable.
```typescript
declare interface LoDashStatic {
at<T extends object>();
};
```
```scala
trait LoDashStatic extends js.Object {
def at[T <: `object`](): js.Dynamic = js.native
}
```
```scala
trait LoDashStatic extends js.Object {
def at[T <: js.Object](): js.Dynamic = js.native
}
```
> Add object type support

- samples/numberlit.ts
- samples/numberlit.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefLexical.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
Converts the number literal type to `Int` or `Double`.
* `Int` if it is valid-integer and does not have the fraction part, , e.g. `1` or `0x1`
* `Double` if it has the fraction part, e.g. `0.1`, `1.0` or `00000000001001000110100`
Compared to the string literal type, the usage seems very low... but not zero, e.g. [Pixi](https://github.com/pixijs/pixi-typescript/blob/d76f75ccef19d46b5a793d73803661c57480a3a7/pixi.js.d.ts#L1735).
> Add number literal type

- src/main/scala/org/scalajs/tools/tsimporter/Main.scala
- src/test/scala/org/scalajs/tools/tsimporter/ImporterSpec.scala
Parsing error of TypeScript kills sbt interactive session. This is inconvenience while developing.
```shell-session
$ echo 'oops' > samples/oops.ts 
$ sbt
sbt:scala-js-ts-importer> test
Parse error at 1.1
'`import'' expected but identifier oops found
oops
$
```
To improve this, I extract core process from `Main.main`, and use it from `ImportSpec`.
> Prevent abnormal exit while running test

- samples/nestedobjectliteraltypes.ts
- samples/nestedobjectliteraltypes.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
- src/main/scala/org/scalajs/tools/tsimporter/sc/Printer.scala
Nested object literal is converted to `any` type. By converting nested object type to anonymous trait, improve its accuracy.
```typescript
declare interface Info {
settings: {
state: {
enable: boolean;
};
};
};
```
```scala
@js.native
trait Info extends js.Object {
var settings: js.Any = js.native
}
```
```scala
@js.native
trait Info extends js.Object {
var settings: Info.settings = js.native
}
@js.native
object Info extends js.Object {
@js.native
trait settings extends js.Object {
var state: settings.state = js.native
}
@js.native
object settings extends js.Object {
@js.native
trait state extends js.Object {
var enable: Boolean = js.native
}
}
}
```
> Improve nested object literal

- samples/objectlit.d.ts
- samples/objectlit.d.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
> Allow numeric literal as property name

- project/build.properties
When I run this locally, the terminal gets screwed up because of sbt/sbt#3453. Updating to sbt 1.1 fixes that issue, making this project more convenient to clone and run.
> Upgrade to sbt 1.1.0 to pull in fix for sbt's stty bug

- samples/booleanlit.d.ts.scala
- samples/duplicateliteraltypes.d.ts
- samples/duplicateliteraltypes.d.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
if needed, duplicate method definitions will still be pruned
> Fix #63: don't early-discard specialized signatures

- samples/enum.d.ts
- samples/enum.d.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
This PR fixes https://github.com/sjrd/scala-js-ts-importer/issues/76 by adding [string enum expression](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) support.
> Fix #76: Add string enum support.

- samples/indexabletypes.d.ts
- samples/indexabletypes.d.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
- src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
This PR fixes #69.
scala-js-ts-importer can convert indexable types, which has index access a.k.a. bracket access.
TypeScript allows indexable types to have `readonly` modifier, so that the types can prevent assignment to their indices.
This PR adds support of readonly indexable types.
```TypeScript
interface A {
[key: string]: string;
}
interface B {
readonly [key: string]: string;
}
```
```Scala
@js.native
trait A extends js.Object {
@JSBracketAccess
def apply(index: String): String = js.native
@JSBracketAccess
def update(index: String, v: String): Unit = js.native
}
@js.native
trait B extends js.Object {
@JSBracketAccess
def apply(index: String): String = js.native
}
```
5 occurences of readonly indexable types are found in DefinitelyTyped, as of 2018-03-23.
```bash
$ git clone …
```
> Fix #69: Support readonly indexable types

- samples/enum.d.ts
- samples/enum.d.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefLexical.scala
This PR fixes #68.
I could not find any TypeScript official docs to explain negative value in enums, but obviously it is supported, since there are lots of occurence in the wild.
```bash
$ git clone https://github.com/DefinitelyTyped/DefinitelyTyped
$ cd https://github.com/DefinitelyTyped/DefinitelyTyped
$ git grep -E "\w+ = -[0-9]+" | wc -l
1247
```
The issue https://github.com/Microsoft/TypeScript/issues/150 might explains TypeScript allows negative value in enums.
> Fix #68: Support negative value in enums

- samples/modifiers.d.ts
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
This PR fixes #80 by adding support for private fields with type annotation.
Private methods and private fields without type annotation are already supported.
> Fix #80: Support private field with type annotation.

- samples/uniontype.d.ts
- samples/uniontype.d.ts.scala
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
I'm fairly confident that my samples demonstrate the desired syntax and outcome, but I'm less confident that the parser implementation is optimal. (It might be, I'm just inexperienced with the parser-combinator library.)
> Fix #70: allow leading | in union type definitions

- build.sbt
- src/main/scala/org/scalajs/tools/tsimporter/Config.scala
- src/main/scala/org/scalajs/tools/tsimporter/Main.scala
Thre are some new feature demands (like #32, #50, #83) that should be user preference.
To add such user preference, new command line options might be required.
This PR adds https://github.com/scopt/scopt as command line parser, so one can add new options easily.
Help message will be 
```bash
sbt:scala-js-ts-importer> run --help
[info] Running org.scalajs.tools.tsimporter.Main --help
Usage: scalajs-ts-importer [options] <input.d.ts> <output.scala> [<package>]
<input.d.ts>    TypeScript type definition file to be read
<output.scala>  Output Scala.js file
<package>       Package name for the output (defaults to "importedjs")
-h, --help      prints help
```
Error message will be
```bash
sbt:scala-js-ts-importer> run foo.ts
[info] Running org.scalajs.tools.tsimporter.Main foo.ts
Error: Missing …
```
> Introduce CLI options parser so that new options can be added easily

- src/main/scala/org/scalajs/tools/tsimporter/Main.scala
`FileReader` is not closed.
If parsing ~.d.ts failed during running/testing, the opened ~.d.ts can not be modified by other process.
This PR resolves the issue.
> Close the FileReader used to read the input file.

- build.sbt
- project/build.properties
- src/main/scala/org/scalajs/tools/tsimporter/Main.scala
Closes #91.
It also addresses [the moved `PagedSeq`](https://github.com/scala/scala-parser-combinators/pull/97)
> Update scala-parser-combinators and Scala/sbt

- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
Mainly to support JDK 11 by updating Scala.js plugin.
> Update dependencies 

- samples/export.d.ts
- src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
Partially adresses #82 regarding [default export](https://www.typescriptlang.org/docs/handbook/modules.html#default-exports)
This PR let parser ignore `export default`.
In future, we may generate some code for default export for utility.
> Ignore "export default IDENTIFIER"
